namespace eCommerceApp.Application.DTOs.Dashboard
{
    /// <summary>
    /// Represents a top-selling product in the dashboard.
    /// </summary>
    public class TopSellingProductDto
    {
        /// <summary>
        /// Gets or sets the rank of the product.
        /// </summary>
        public int Rank { get; set; }

        /// <summary>
        /// Gets or sets the product ID.
        /// </summary>
        public int ProductId { get; set; }

        /// <summary>
        /// Gets or sets the product name.
        /// </summary>
        public string ProductName { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the product image URL.
        /// </summary>
        public string? ImageUrl { get; set; }

        /// <summary>
        /// Gets or sets the total quantity of the product sold.
        /// </summary>
        public int TotalSoldQuantity { get; set; }

        /// <summary>
        /// Gets or sets the total revenue generated by the product.
        /// </summary>
        public decimal TotalRevenue { get; set; }
    }
}
